In [23]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [24]:
env = gym.make("FrozenLake-v0")

In [25]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
num_episodes = 20000
max_num_steps_per_episode = 100

learning_rate = 0.3
discount_rate = 0.97

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [27]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_num_steps_per_episode):
        
        #exploration -- exploitation tradeoff
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate and ~np.all(q_table[state,:]==0):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #update q_table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #exploration decay rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.05100000000000004
2000 :  0.16500000000000012
3000 :  0.32800000000000024
4000 :  0.46100000000000035
5000 :  0.5660000000000004
6000 :  0.5530000000000004
7000 :  0.6240000000000004
8000 :  0.5850000000000004
9000 :  0.5960000000000004
10000 :  0.6550000000000005
11000 :  0.6430000000000005
12000 :  0.6270000000000004
13000 :  0.5960000000000004
14000 :  0.6190000000000004
15000 :  0.5960000000000004
16000 :  0.6530000000000005
17000 :  0.6280000000000004
18000 :  0.6090000000000004
19000 :  0.5940000000000004
20000 :  0.6440000000000005


In [28]:
print(q_table)

[[0.23928343 0.22701256 0.22616935 0.22615102]
 [0.15416877 0.09091361 0.1219069  0.20077744]
 [0.12238096 0.12263547 0.16328252 0.18116614]
 [0.05768508 0.08479469 0.0667308  0.16935802]
 [0.25751991 0.06078553 0.20337647 0.208975  ]
 [0.         0.         0.         0.        ]
 [0.19868665 0.04442718 0.18773295 0.0157904 ]
 [0.         0.         0.         0.        ]
 [0.212335   0.17404526 0.24540934 0.27778346]
 [0.29524303 0.38547938 0.34658437 0.25082056]
 [0.38757865 0.28525748 0.06062473 0.25381234]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3533114  0.3304305  0.48321164 0.27717613]
 [0.55695076 0.64641678 0.53502022 0.55247498]
 [0.         0.         0.         0.        ]]


In [ ]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(1000):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_num_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break            

        # Set new state
        state = new_state
        
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
